# My theme
theme: jekyll-theme-architect

# Use GFM (from kramdown or GFM)
markdown: GFM

# Specific for BayesicFitting
title: [BayesicFitting]
description: [Model Fitting and Evidence Calculation]
examples: 
  - img: ./docs/images/rijntemp.png
    cap: "Average temperature of the Rhine"
  - img: ./docs/images/Julius.png
    cap: "Light absorption by tea"
  - img: ./docs/images/HD76700.png
    cap: "Exoplanet around HD76700"
  - img: ./docs/images/83Aqr.png
    cap: "Orbit of double star 83 Aqr"
  - img: ./docs/images/Gregory.png
    cap: "A signal or not"
  - img: ./docs/images/corona.png
    cap: "Early Covid mortality rate"
  - img: ./docs/images/boyle.png
    cap: "Boyle's law in his own data"
  - img: ./docs/images/methanol.png
    cap: "Alias in spectral continuum"
  - img: ./docs/images/HD2039.png
    cap: "Exoplanet on HD 2039"
  - img: ./docs/images/spectrallines.png
    cap: "Lines in methanol spectrum"

