[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "BayesicFitting"
version = "3.2.5"
dependencies = [
    'numpy >= 1.9',
    'matplotlib >= 2.0',
    'scipy >= 1.0',
    'astropy >= 2.0',
    'future'
]
authors = [
    { name = "Do Kester", email = "dokester@home.nl" }
]
description = "A Toolbox for Bayesian Fitting and Evidence Calculation"
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-or-later"
keywords = [
    'Bayesian', 'modeling', 'evidence', 'statistics', 'analysis',
    'regression', 'inference', 'optimization','nested sampling', 'fitting'
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering"
]

[project-urls]
homepage = "https://dokester.github.io/BayesicFitting/"

#[tool.setuptools]
#packages=[
#    'BayesicFitting', 'BayesicFitting/source', 'BayesicFitting/source/kernels',
#    'BayesicFitting/test', 'BayesicFitting/examples'
#]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    "BayesicFitting/TBD-examples",
    "BayesicFitting/TBD-tests",
    "BayesicFitting/__pycache__",
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "_build",
    "dist",
    "docs",
    "REFDOC",
    "refman"
]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.8
target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "NPY201"]

# F401 : imported not used
# E701 : multiple statements on one line
ignore = ["F401", "E701"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

